### ISSUE TITLE
Compilation fails on arm64 architecture

### ISSUE THREAD

**Issue by alessandrothea** [art-daq/trace#17]
Hi,

When building `trace` on alma9 on an arm64 machine, the compilation fails.
A quick look at the code seems to indicate that the cause are the arm-specific if statements like:

```c++
if defined(__arm__) 
```
that are not activated since the preprocessor variable for arm64 architecture is `__aarch64__` and not `__arm__`.
Would it be possible to patch these statements to cover the arm64 case as well?
Thank you.

Alessandro

**Comment by ron003** [comment]
@alessandrothea I'm going to try to do this and test it. I am trying to get access to an `__aarch64__` system. Eric mentioned that you may have an alma9 container (or VM image) for an M1 Mac. I can get a loaner from our service desk. It might be good to try to duplicate your build environment.
